### ISSUE TITLE
wrong argument when connecting to TD server

### ISSUE THREAD

**Issue by DianaZhao** [freemine/taos_odbc#2]
there is a bug in conn.c  _do_conn_connect
conn->taos = CALL_taos_connect(cfg->ip, cfg->uid, cfg->pwd, cfg->db, cfg->port);
cfg do not have a field named "ip",  you have assigned ServerName arg to cfg->dsn in conn_connect, which passed from SQLConnect. 
so the connect always fails.

**Comment by freemine** [comment]
please check src/inc/conn.h, struct connection_cfg_s is defined there, and it does have both `ip` and `dsn` as it's field.
this `connection_cfg_s` is for internal use only, and as designed, the only way to set `ip` is via ODBC's connection string, such as SQLDriverConnect(..., "Driver={TAOS_ODBC_DRIVER};Server=localhost:6030;",...).
the other way is via SQLConnect("DSN=..."), when in runtime, `taos_odbc` would check entries defined by DSN, if there's an entry "SERVER=...", then, connection_cfg_s::ip would be set.

FYI, for how to use SQLDriverConnect, you can check test case in
```
tests/c/api_test.c:491:  CHK2(test_sql_driver_conn, connh, "Driver={TAOS_ODBC_DRIVER};Server=127.0.0.1:6030", 0);
```

wish this helps.

**Comment by freemine** [comment]
btw, according to what i know from tdengine's `taos_connect` in taos.h,
if you specify cfg->ip = NULL, it'll fallback to localhost.

thus, if you failed to connect, mostly likely you have not installed and started TDengine on localhost.
FYI, if you are testing on windows platforom, please follow TDengines' document to build, and don't forget to start TDengine
service.
```
sc start taosd
```

wish this helps.

**Comment by freemine** [comment]
seems this has been inactive for too long, we choose to close it.
